from __future__ import annotations

NO_AUTO_LIVE_START_STATEMENT = "NO AUTO LIVE START - MANUAL GATED LIVE SAFETY ONLY"
NOT_FINANCIAL_ADVICE_STATEMENT = "LIVE SAFETY OUTPUT IS OPERATIONAL EVIDENCE, NOT FINANCIAL ADVICE"
LIVE_RISK_CONFIRM = "I_UNDERSTAND_LIVE_SPOT_TRADING_RISK"
REAL_ORDER_CONFIRM = "I_UNDERSTAND_THIS_WILL_PLACE_A_REAL_BINANCE_SPOT_ORDER"
CONTROLLED_SESSION_CONFIRM = "I_UNDERSTAND_CONTROLLED_LIVE_SESSION_RISK"
CONTROLLED_ORDER_CONFIRM = "I_UNDERSTAND_THIS_PLACES_A_REAL_BINANCE_SPOT_ORDER"
NO_UNATTENDED_LIVE_STATEMENT = "NO UNATTENDED LIVE TRADING - CONTROLLED SESSION ONLY"
NO_AUTO_SCALE_STATEMENT = "NO AUTOMATIC LIVE SCALE-UP - OPERATOR APPROVAL REQUIRED"
LIVE_SCALING_APPROVAL_CONFIRM = "I_APPROVE_THIS_LIVE_SCALING_DECISION"
