from __future__ import annotations

NO_LIVE_ORDER_STATEMENT = "AI DOCTOR NEVER PLACES ORDERS OR STARTS LIVE SESSIONS"
LOCAL_ONLY_STATEMENT = "AI DOCTOR DEBUG BUNDLES STAY LOCAL ONLY"
SAFE_ENV = {"LIVE_TRADING_ENABLED": "false", "KILL_SWITCH": "true"}

